name: Gitleaks

on:
  push:
    branches: [ main, develop, "feat/**" ]
  pull_request:
    branches: [ main, develop, "feat/**" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | \
          grep "browser_download_url.*linux_x64.tar.gz" | \
          cut -d '"' -f 4 | \
          xargs wget -O gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Gitleaks scan
        run: gitleaks detect --source=. --no-banner --redact
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

